---
name: Build and Deploy To Server
on:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v2
      - name: Builds and Deploys Node App To Server
        uses: Adophilus/actions@64633103c7bb442527f588ec6f950fccf7a52c58
        with:
          deploy-path: ${{ secrets.SERVER_DEPLOY_PATH }}
