---
name: Build and Deploy To Server
on:
- push
- workflow_dispatch
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v3
      - name: Upload workspace as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .
          retention-days: 1
  build-and-deploy:
    needs: checkout-repo
    uses: Adophilus/actions/.github/workflows/node-build-and-deploy-ssh.yml@main
    with:
      build-script: build
      artifact-name: workspace
    secrets:
      SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
