---
name: Build and Deploy To Server
on:
  push:
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v2
  build-and-deploy:
    needs: checkout-repo
    uses: Adophilus/actions/.github/workflows/node-build-and-deploy-ssh.yml@main
    with:
      deploy-path: ${{ secrets.SERVER_DEPLOY_PATH }}
